# https://taskfile.dev/#/installation
version: 3

# env - dotenv, global, local
dotenv: ['.env']

# tasks
tasks:
  all:
    cmds:
      - task: format
      - task: build
      - task: tests
      - task: docs

  format:
    - cmake-format --in-place
      ./cmake/program_options/*.cmake
      ./cmake/program_options/src/*.cmake
      ./cmake/dependency_options/*.cmake
      ./lib/CMakeLists.txt
      ./app/CMakeLists.txt
      ./tests/CMakeLists.txt
    - clang-format -i ./lib/*.cc ./app/*.cc --style=file

  build:
    - cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Debug
    - cmake --build build

  build-release:
    - cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release
    - cmake --build build

  run:
    - cmake --build build
    - ./build/app/starter_app

  install:
    - sudo cmake --build build --target install

  tests:
    - cmake --build build --target ctest

  docs:
    - cmake --build build --target doxygen-docs
    - cp -r ./build/html ./docs

  clean:
    - rm -rf build libdeps/src



